# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/3d_printer_db  # Adjust as needed
    volumes:
      - ./backend:/app  # Mount the backend directory for live updates
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 3d_printer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 in the container